### ISSUE TITLE
gpart does not respect docdir.

### ISSUE THREAD

**Issue by orbea** [baruch/gpart#10]
I recently compiled gpart from source on slackware linux and found that gpart does not respect "--docdir", instead it uses "--datadir".  Though it still gets this wrong because instead of respecting something like "--datadir=/usr/doc/$PRGNAM-$VERSION", it will stick them in "/usr/doc/${PRGNAM}-$VERSION/doc/gpart" making me have to add a line like this to my slackbuild, "rm -rf $PKG/usr/doc/${PRGNAM}-$VERSION/doc".

This is not a deal breaker, but can it still get fixed anyways?  Thanks!

**Comment by baruch** [comment]
Fixed now, no idea why I overrode docdir in the first place.

**Comment by orbea** [comment]
Awesome, thanks for your quick fix.  I applied the commit as a patch to my slackbuild and confirm it works.

**Comment by baruch** [comment]
Great! good to know it works now.
