### ISSUE TITLE
v0.2.2 identifies itself as v0.2.1

### ISSUE THREAD

**Issue by ian-abbott** [baruch/gpart#6]
I'm not sure if v0.2.2 has been formally released but at least Debian has a package for it.

The version was not updated in configure.ac so the program still reports its version as v0.2.1.

Anyway, I guess it's too late to fix it now (unless distros want to apply their own patch), but I thought I'd raise the issue as a reminder for the next release!

**Comment by baruch** [comment]
Thanks! will try to keep that in mind.
